import { createStore } from 'vuex'


const store = createStore({
    state() {
        return {
            products: [
                {
                    id: 1,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                    discount: 10,
                },
                {
                    id: 2,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                    discount: 50,
                },
                {
                    id: 3,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 4,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 5,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 6,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 7,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 8,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 9,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 10,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 11,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 12,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                    discount: 1,
                },
                {
                    id: 13,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                    discount: 1,
                },
                {
                    id: 14,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 15,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 16,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 17,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 18,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 19,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 20,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 21,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 22,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 23,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 24,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                    discount: 5,
                },
                {
                    id: 25,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                },
                {
                    id: 26,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 27,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 28,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 29,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 30,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 31,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 32,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 33,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 34,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 35,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 36,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 37,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 38,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 39,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 40,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 41,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 42,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 43,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 44,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 45,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 46,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 47,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 48,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 49,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 50,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 51,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 52,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 53,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 54,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 55,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 56,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 57,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 58,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 59,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 60,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 61,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 62,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 63,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 64,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 65,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 66,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 67,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 68,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 69,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 70,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 71,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 72,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 73,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 74,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 75,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 76,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 77,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 78,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 79,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 80,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 81,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 82,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 83,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 84,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 85,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    discount: 10,
                    count: 1,
                },
                {
                    id: 86,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 87,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 88,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 89,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 90,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 91,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    count: 1,
                },
                {
                    id: 92,
                    type: "Complect",
                    title: "Telefon",
                    price: 15000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    discount: 10,
                    count: 1,
                },
                {
                    id: 93,
                    type: "Техника",
                    title: "Ноутбук",
                    price: 7000000,
                    about: 'Доступно только 4 штуки, и сейчас это есть у более 20 человек',
                    like: false,
                    cart: false,
                    checkbox: false,
                    discount: 10,
                    count: 1,
                },
            ]
        }
    },
    mutations: {
        ADD_TO_CART(state, item) {
            if (item.cart == false) {
                item.cart = true;
            } else {
                item.count++
            }
        },
        REMOVE_CHECKED(state) { 
            for (const item in state.products) {
                if (state.products[item].checkbox == true) {
                    state.products[item].checkbox = false;
                    state.products[item].like = false;
                    state.products[item].count = 1;
                }
            }
        }
    },
})

export default store